// Contenu pédagogique : Darija (arabe marocain)
// Remarque : la Darija ne possède pas d'orthographe latine standardisée.
// La transcription "latin" utilisée ici est une transcription phonétique
// courante (le "3" = ع, le "7" = ح, le "9"/"q" = ق).

const CATEGORIES = [
  {
    id: "salutations",
    label: "Salutations",
    emoji: "👋",
    kidFriendly: true,
    items: [
      { fr: "Bonjour / Salut", latin: "Salam", arabic: "السلام", emoji: "👋" },
      { fr: "Comment ça va ?", latin: "Kidayer? (homme) / Kidayra? (femme)", arabic: "كيداير؟ / كيدايرة؟", emoji: "🙂" },
      { fr: "Ça va bien, merci", latin: "La bas, lhamdulillah", arabic: "لا باس، الحمد لله", emoji: "😊" },
      { fr: "Merci", latin: "Choukran", arabic: "شكرا", emoji: "🙏" },
      { fr: "S'il te plaît", latin: "3afak", arabic: "عافاك", emoji: "🤲" },
      { fr: "Oui", latin: "Iyeh", arabic: "ايه", emoji: "✅" },
      { fr: "Non", latin: "La", arabic: "لا", emoji: "❌" },
      { fr: "Au revoir", latin: "Bslama", arabic: "بسلامة", emoji: "👋" },
      { fr: "Bienvenue", latin: "Marhba", arabic: "مرحبا", emoji: "🤗" },
      { fr: "Bonsoir", latin: "Msa lkhir", arabic: "مسا الخير", emoji: "🌆" },
      { fr: "Bonne journée", latin: "Nhark mzyan", arabic: "نهارك مزيان", emoji: "☀️" },
      { fr: "Excusez-moi / Pardon", latin: "Smeh lia", arabic: "سمح ليا", emoji: "🙇" },
      { fr: "Ce n'est rien / pas de problème", latin: "Machi muchkil", arabic: "ماشي مشكل", emoji: "🤷‍♂️" },
      { fr: "De rien", latin: "Bla jmil", arabic: "بلا جميل", emoji: "😊" },
      { fr: "Enchanté(e)", latin: "Metcharfin", arabic: "متشرفين", emoji: "🤝" },
      { fr: "Félicitations", latin: "Mabrouk", arabic: "مبروك", emoji: "🎉" },
      { fr: "Bon appétit", latin: "Bsaha", arabic: "بالصحة", emoji: "🍽️" },
      { fr: "À bientôt", latin: "Nchoufek qriban", arabic: "نشوفك قريبا", emoji: "👋" },
    ],
  },
  {
    id: "famille",
    label: "Famille",
    emoji: "👨‍👩‍👧‍👦",
    kidFriendly: true,
    items: [
      { fr: "Papa", latin: "Baba", arabic: "بابا", emoji: "👨", tags: ["any", "seeable"] },
      { fr: "Maman", latin: "Mama / Mma", arabic: "ماما", emoji: "👩", tags: ["any", "seeable"] },
      { fr: "Frère", latin: "Khoya", arabic: "خويا", emoji: "👦", tags: ["any", "seeable"] },
      { fr: "Sœur", latin: "Khti", arabic: "ختي", emoji: "👧", tags: ["any", "seeable"] },
      { fr: "Fils", latin: "Weld", arabic: "ولد", emoji: "👦", tags: ["any", "seeable"] },
      { fr: "Fille", latin: "Bnt", arabic: "بنت", emoji: "👧", tags: ["any", "seeable"] },
      { fr: "Grand-père", latin: "Jeddi", arabic: "جدي", emoji: "👴", tags: ["any", "seeable"] },
      { fr: "Grand-mère", latin: "Jeddati", arabic: "جدتي", emoji: "👵", tags: ["any", "seeable"] },
      { fr: "Famille", latin: "3a'ila", arabic: "عائلة", emoji: "👨‍👩‍👧‍👦", tags: ["any"] },
      { fr: "Oncle (paternel)", latin: "3mi", arabic: "عمي", emoji: "👨", tags: ["any", "seeable"] },
      { fr: "Oncle (maternel)", latin: "Khali", arabic: "خالي", emoji: "👨", tags: ["any", "seeable"] },
      { fr: "Tante (paternelle)", latin: "3mti", arabic: "عمتي", emoji: "👩", tags: ["any", "seeable"] },
      { fr: "Tante (maternelle)", latin: "Khalti", arabic: "خالتي", emoji: "👩", tags: ["any", "seeable"] },
      { fr: "Cousin", latin: "Weld 3mi", arabic: "ولد عمي", emoji: "🧑", tags: ["any", "seeable"] },
      { fr: "Cousine", latin: "Bnt 3mi", arabic: "بنت عمي", emoji: "🧑", tags: ["any", "seeable"] },
      { fr: "Mari", latin: "Rajel", arabic: "راجل", emoji: "🤵", tags: ["any", "seeable"] },
      { fr: "Femme (épouse)", latin: "Mra", arabic: "مرا", emoji: "👰", tags: ["any", "seeable"] },
      { fr: "Bébé", latin: "Drri sghir", arabic: "دري صغير", emoji: "👶", tags: ["any", "seeable"] },
    ],
  },
  {
    id: "nombres",
    label: "Nombres",
    emoji: "🔢",
    kidFriendly: true,
    items: [
      { fr: "1", latin: "Wahed", arabic: "واحد", emoji: "1️⃣" },
      { fr: "2", latin: "Jouj", arabic: "جوج", emoji: "2️⃣" },
      { fr: "3", latin: "Tlata", arabic: "تلاتة", emoji: "3️⃣" },
      { fr: "4", latin: "Rb3a", arabic: "ربعة", emoji: "4️⃣" },
      { fr: "5", latin: "Khamsa", arabic: "خمسة", emoji: "5️⃣" },
      { fr: "6", latin: "Stta", arabic: "ستة", emoji: "6️⃣" },
      { fr: "7", latin: "Sb3a", arabic: "سبعة", emoji: "7️⃣" },
      { fr: "8", latin: "Tmnya", arabic: "تمنية", emoji: "8️⃣" },
      { fr: "9", latin: "Tsa3oud", arabic: "تسعود", emoji: "9️⃣" },
      { fr: "10", latin: "3achra", arabic: "عشرة", emoji: "🔟" },
      { fr: "11", latin: "Hdach", arabic: "احداش", emoji: "🔢" },
      { fr: "12", latin: "Tnach", arabic: "طناش", emoji: "🔢" },
      { fr: "13", latin: "Tlttach", arabic: "تلطاش", emoji: "🔢" },
      { fr: "14", latin: "Rba3tach", arabic: "ربعطاش", emoji: "🔢" },
      { fr: "15", latin: "Khmstach", arabic: "خمسطاش", emoji: "🔢" },
      { fr: "16", latin: "Sttach", arabic: "سطاش", emoji: "🔢" },
      { fr: "17", latin: "Sb3tach", arabic: "سبعطاش", emoji: "🔢" },
      { fr: "18", latin: "Tmntach", arabic: "تمنطاش", emoji: "🔢" },
      { fr: "19", latin: "Ts3tach", arabic: "تسعطاش", emoji: "🔢" },
      { fr: "20", latin: "3achrin", arabic: "عشرين", emoji: "🔢" },
      { fr: "30", latin: "Tlatin", arabic: "تلاتين", emoji: "🔢" },
      { fr: "40", latin: "Rb3in", arabic: "ربعين", emoji: "🔢" },
      { fr: "50", latin: "Khamsin", arabic: "خمسين", emoji: "🔢" },
      { fr: "100", latin: "Miya", arabic: "مية", emoji: "🔢" },
      { fr: "Premier", latin: "Lowel", arabic: "الأول", emoji: "🥇" },
      { fr: "Deuxième", latin: "Tani", arabic: "الثاني", emoji: "🥈" },
      { fr: "Troisième", latin: "Talet", arabic: "الثالث", emoji: "🥉" },
      { fr: "Dernier", latin: "Lakhir", arabic: "الأخير", emoji: "🏁" },
    ],
  },
  {
    id: "couleurs",
    label: "Couleurs",
    emoji: "🎨",
    kidFriendly: true,
    items: [
      { fr: "Rouge", latin: "Hmer", arabic: "احمر", emoji: "🔴" },
      { fr: "Bleu", latin: "Zrq", arabic: "ازرق", emoji: "🔵" },
      { fr: "Vert", latin: "Khdr", arabic: "اخضر", emoji: "🟢" },
      { fr: "Jaune", latin: "Sfr", arabic: "اصفر", emoji: "🟡" },
      { fr: "Noir", latin: "Kahel", arabic: "كحل", emoji: "⚫" },
      { fr: "Blanc", latin: "Byed", arabic: "بيض", emoji: "⚪" },
    ],
  },
  {
    id: "animaux",
    label: "Animaux",
    emoji: "🐾",
    kidFriendly: true,
    items: [
      { fr: "Chat", latin: "Mouch", arabic: "موش", emoji: "🐱", tags: ["any", "seeable"] },
      { fr: "Chien", latin: "Kelb", arabic: "كلب", emoji: "🐶", tags: ["any", "seeable"] },
      { fr: "Oiseau", latin: "Tir", arabic: "طير", emoji: "🐦", tags: ["any", "seeable"] },
      { fr: "Poisson", latin: "Hout", arabic: "حوت", emoji: "🐟", tags: ["any", "seeable"] },
      { fr: "Cheval", latin: "3awd", arabic: "عود", emoji: "🐴", tags: ["any", "seeable"] },
      { fr: "Vache", latin: "Bagra", arabic: "بكرة", emoji: "🐄", tags: ["any", "seeable"] },
    ],
  },
  {
    id: "nourriture",
    label: "Nourriture",
    emoji: "🍎",
    kidFriendly: true,
    items: [
      { fr: "Pain", latin: "Khobz", arabic: "خبز", emoji: "🍞", tags: ["any", "food"] },
      { fr: "Eau", latin: "Ma", arabic: "ما", emoji: "💧", tags: ["any", "drink"] },
      { fr: "Lait", latin: "Hlib", arabic: "حليب", emoji: "🥛", tags: ["any", "drink"] },
      { fr: "Pomme", latin: "Tffah", arabic: "تفاح", emoji: "🍎", tags: ["any", "food"] },
      { fr: "Sucre", latin: "Sokkar", arabic: "سكر", emoji: "🍬", tags: ["any", "food"] },
      { fr: "Thé", latin: "Atay", arabic: "أتاي", emoji: "🍵", tags: ["any", "drink"] },
      { fr: "Café", latin: "Qahwa", arabic: "قهوة", emoji: "☕", tags: ["any", "drink"] },
      { fr: "Viande", latin: "Lham", arabic: "لحم", emoji: "🍖", tags: ["any", "food"] },
      { fr: "Légumes", latin: "Khodra", arabic: "خضرة", emoji: "🥕", tags: ["any", "food"] },
      { fr: "Fruits", latin: "Fakia", arabic: "فاكية", emoji: "🍇", tags: ["any", "food"] },
      { fr: "Riz", latin: "Rz", arabic: "رز", emoji: "🍚", tags: ["any", "food"] },
      { fr: "Œuf", latin: "Bida", arabic: "بيضة", emoji: "🥚", tags: ["any", "food"] },
    ],
  },
  {
    id: "corps",
    label: "Corps",
    emoji: "🙆",
    kidFriendly: true,
    items: [
      { fr: "Tête", latin: "Ras", arabic: "راس", emoji: "🧠" },
      { fr: "Main", latin: "Yed", arabic: "يد", emoji: "✋" },
      { fr: "Pied", latin: "Rjel", arabic: "رجل", emoji: "🦶" },
      { fr: "Ventre", latin: "Kerch", arabic: "كرش", emoji: "🫃" },
      { fr: "Œil / Yeux", latin: "3in", arabic: "عين", emoji: "👁️" },
      { fr: "Bouche", latin: "Fum", arabic: "فم", emoji: "👄" },
      { fr: "Nez", latin: "Nif", arabic: "نيف", emoji: "👃" },
      { fr: "Oreille", latin: "Wdn", arabic: "ودن", emoji: "👂" },
    ],
  },
  {
    id: "famille_visite",
    label: "Avec la famille",
    emoji: "🏡",
    kidFriendly: true,
    items: [
      { fr: "Je peux jouer dehors ?", latin: "Wach ne9der nl3ab bra?", arabic: "واش نقدر نلعب برا؟", emoji: "🤸" },
      { fr: "Aide-moi s'il te plaît", latin: "3awenni 3afak", arabic: "عاونني عافاك", emoji: "🙋" },
      { fr: "Un bisou", latin: "Bosa", arabic: "بوسة", emoji: "😘" },
      { fr: "Un câlin", latin: "Hidn", arabic: "حضن", emoji: "🤗" },
      { fr: "Je t'aime", latin: "Kanbghik", arabic: "كنبغيك", emoji: "❤️" },
      { fr: "C'est délicieux !", latin: "Bnina!", arabic: "بنينة!", emoji: "😋" },
      { fr: "Je suis rassasié(e), merci", latin: "Chbe3t, choukran", arabic: "شبعت، شكرا", emoji: "🍽️" },
      { fr: "Bonne nuit", latin: "Tsbah 3la khir", arabic: "تصبح على خير", emoji: "🌙" },
    ],
  },
  {
    id: "phrases",
    label: "Phrases utiles",
    emoji: "💬",
    kidFriendly: false,
    items: [
      { fr: "Je m'appelle...", latin: "Smiti...", arabic: "سميتي...", emoji: "💬" },
      { fr: "Comment tu t'appelles ?", latin: "Ach smitek?", arabic: "اش سميتك؟", emoji: "❓" },
      { fr: "Je ne comprends pas", latin: "Ma fhemtch", arabic: "ما فهمتش", emoji: "🤷" },
      { fr: "Je ne parle pas bien Darija", latin: "Ma ne3reftch nhder Darija mzyan", arabic: "ما نعرفتش نهضر الدارجة مزيان", emoji: "🗣️" },
      { fr: "Où sont les toilettes ?", latin: "Fin kayn lbit lma?", arabic: "فين كاين البيت الما؟", emoji: "🚻" },
      { fr: "C'est combien ?", latin: "Bcha7al?", arabic: "بشحال؟", emoji: "💰" },
      { fr: "J'ai faim", latin: "Fiya jou3", arabic: "فيا جوع", emoji: "🍽️" },
      { fr: "J'ai soif", latin: "Fiya 3tech", arabic: "فيا عطش", emoji: "🥤" },
      { fr: "Je suis fatigué(e)", latin: "Ana 3eyan", arabic: "انا عيان", emoji: "😴" },
      { fr: "Je suis malade", latin: "Ana mrid", arabic: "انا مريض", emoji: "🤒" },
      { fr: "Il me faut...", latin: "Khessni...", arabic: "خصني...", emoji: "🙏" },
    ],
  },
  {
    id: "questions",
    label: "Mots interrogatifs",
    emoji: "❓",
    kidFriendly: false,
    items: [
      { fr: "Qui ?", latin: "Chkoun?", arabic: "شكون؟", emoji: "❓" },
      { fr: "Quoi ?", latin: "Ach?", arabic: "اش؟", emoji: "❓" },
      { fr: "Où ?", latin: "Fin?", arabic: "فين؟", emoji: "❓" },
      { fr: "Quand ?", latin: "Fuqach?", arabic: "فوقاش؟", emoji: "❓" },
      { fr: "Pourquoi ?", latin: "3lach?", arabic: "علاش؟", emoji: "❓" },
      { fr: "Comment ?", latin: "Kifach?", arabic: "كيفاش؟", emoji: "❓" },
      { fr: "Combien ?", latin: "Chhal?", arabic: "شحال؟", emoji: "❓" },
    ],
  },
  {
    id: "verbes",
    label: "Verbes courants",
    emoji: "🏃",
    kidFriendly: false,
    items: [
      { fr: "Je veux", latin: "Bghit", arabic: "بغيت", emoji: "🙏" },
      { fr: "Je peux", latin: "Nqder", arabic: "نقدر", emoji: "💪" },
      { fr: "Je sais", latin: "3reft", arabic: "عرفت", emoji: "🧠" },
      { fr: "Je vais (aller)", latin: "Ghadi nmchi", arabic: "غادي نمشي", emoji: "🚶" },
      { fr: "Je viens", latin: "Ghadi nji", arabic: "غادي نجي", emoji: "🙋" },
      { fr: "Je parle", latin: "Kanhder", arabic: "كنهضر", emoji: "🗣️" },
      { fr: "Je mange", latin: "Kanakol", arabic: "كناكل", emoji: "🍽️" },
      { fr: "Je bois", latin: "Kanchrb", arabic: "كنشرب", emoji: "🥤" },
      { fr: "Je dors", latin: "Kanne3s", arabic: "كننعس", emoji: "😴" },
      { fr: "Je travaille", latin: "Kankhdem", arabic: "كنخدم", emoji: "💼" },
      { fr: "J'achète", latin: "Kanchri", arabic: "كنشري", emoji: "🛍️" },
      { fr: "Je donne", latin: "Kan3ti", arabic: "كنعطي", emoji: "🤲" },
    ],
  },
  {
    id: "adjectifs",
    label: "Adjectifs",
    emoji: "✨",
    kidFriendly: false,
    items: [
      { fr: "Grand", latin: "Kbir", arabic: "كبير", emoji: "📏" },
      { fr: "Petit", latin: "Sghir", arabic: "صغير", emoji: "🤏" },
      { fr: "Beau / Joli", latin: "Zwin", arabic: "زوين", emoji: "😍" },
      { fr: "Content", latin: "Farhan", arabic: "فرحان", emoji: "😄" },
      { fr: "Fatigué", latin: "3eyan", arabic: "عيان", emoji: "😴" },
      { fr: "Chaud", latin: "Skhoun", arabic: "سخون", emoji: "🔥" },
      { fr: "Froid", latin: "Bared", arabic: "بارد", emoji: "❄️" },
      { fr: "Bon / délicieux", latin: "Mzyan", arabic: "مزيان", emoji: "👍" },
      { fr: "Cher", latin: "Ghali", arabic: "غالي", emoji: "💸" },
      { fr: "Pas cher", latin: "Rkhis", arabic: "رخيص", emoji: "🪙" },
    ],
  },
  {
    id: "temps",
    label: "Temps & Calendrier",
    emoji: "📅",
    kidFriendly: false,
    items: [
      { fr: "Aujourd'hui", latin: "Lyoum", arabic: "اليوم", emoji: "📅" },
      { fr: "Demain", latin: "Ghda", arabic: "غدا", emoji: "➡️" },
      { fr: "Hier", latin: "Lbareh", arabic: "لبارح", emoji: "⬅️" },
      { fr: "Maintenant", latin: "Daba", arabic: "دابا", emoji: "⏰" },
      { fr: "Matin", latin: "Sbah", arabic: "صباح", emoji: "🌅" },
      { fr: "Soir", latin: "3chiya", arabic: "عشية", emoji: "🌆" },
      { fr: "Semaine", latin: "Simana", arabic: "سيمانة", emoji: "🗓️" },
      { fr: "Lundi", latin: "Tnin", arabic: "تنين", emoji: "🗓️" },
      { fr: "Mardi", latin: "Tlat", arabic: "تلات", emoji: "🗓️" },
      { fr: "Mercredi", latin: "Larb3a", arabic: "لاربعا", emoji: "🗓️" },
      { fr: "Jeudi", latin: "Lkhmis", arabic: "لخميس", emoji: "🗓️" },
      { fr: "Vendredi", latin: "Jjm3a", arabic: "جمعة", emoji: "🗓️" },
      { fr: "Samedi", latin: "Sebt", arabic: "سبت", emoji: "🗓️" },
      { fr: "Dimanche", latin: "7ed", arabic: "حد", emoji: "🗓️" },
      { fr: "Mois", latin: "Chher", arabic: "شهر", emoji: "🌙" },
      { fr: "Année", latin: "3am", arabic: "عام", emoji: "🎊" },
      { fr: "Avant-hier", latin: "Wellbareh", arabic: "ولبارح", emoji: "⏪" },
      { fr: "Après-demain", latin: "Ba3d ghda", arabic: "بعد غدا", emoji: "⏩" },
    ],
  },
  {
    id: "maison",
    label: "Maison",
    emoji: "🏠",
    kidFriendly: false,
    items: [
      { fr: "Maison", latin: "Dar", arabic: "دار", emoji: "🏠" },
      { fr: "Chambre", latin: "Bit", arabic: "بيت", emoji: "🛏️" },
      { fr: "Cuisine", latin: "Kouzina", arabic: "كوزينة", emoji: "🍳" },
      { fr: "Salle de bain", latin: "Hmam", arabic: "حمام", emoji: "🚿" },
      { fr: "Porte", latin: "Bab", arabic: "باب", emoji: "🚪" },
      { fr: "Table", latin: "Tabla", arabic: "طابلة", emoji: "🪑" },
      { fr: "Chaise", latin: "Korsi", arabic: "كرسي", emoji: "🪑" },
      { fr: "Lit", latin: "Namousiya", arabic: "ناموسية", emoji: "🛏️" },
    ],
  },
  {
    id: "marche",
    label: "Au marché",
    emoji: "🛒",
    kidFriendly: false,
    items: [
      { fr: "Marché", latin: "Souq", arabic: "سوق", emoji: "🛒" },
      { fr: "Argent", latin: "Flouss", arabic: "فلوس", emoji: "💵" },
      { fr: "C'est trop cher", latin: "Ghali bezaf", arabic: "غالي بزاف", emoji: "😬" },
      { fr: "Un peu moins ?", latin: "Naqas chwiya?", arabic: "نقص شوية؟", emoji: "🤏" },
      { fr: "D'accord", latin: "Wakha", arabic: "واخا", emoji: "👌" },
      { fr: "Petite monnaie", latin: "Sarf", arabic: "صرف", emoji: "🪙" },
    ],
  },
  {
    id: "expressions",
    label: "Expressions courantes",
    emoji: "🗨️",
    kidFriendly: false,
    items: [
      { fr: "Si Dieu le veut", latin: "InchaAllah", arabic: "ان شاء الله", emoji: "🙏" },
      { fr: "Dieu merci", latin: "Hamdoulillah", arabic: "الحمد لله", emoji: "🙏" },
      { fr: "Au nom de Dieu (avant de manger)", latin: "Bismillah", arabic: "بسم الله", emoji: "🍽️" },
      { fr: "Joli compliment protecteur", latin: "Machallah", arabic: "ماشاء الله", emoji: "✨" },
      { fr: "Je le jure", latin: "Wallah", arabic: "والله", emoji: "🤞" },
      { fr: "Allons-y", latin: "Yallah", arabic: "يالله", emoji: "🏃" },
      { fr: "Ça suffit / stop", latin: "Safi", arabic: "صافي", emoji: "✋" },
      { fr: "Beaucoup", latin: "Bezaf", arabic: "بزاف", emoji: "📈" },
      { fr: "Un peu", latin: "Chwiya", arabic: "شوية", emoji: "🤏" },
      { fr: "Seulement", latin: "Ghir", arabic: "غير", emoji: "☝️" },
    ],
  },
  {
    id: "transport",
    label: "Transport",
    emoji: "🚗",
    kidFriendly: false,
    items: [
      { fr: "Voiture", latin: "Tomobil", arabic: "طوموبيل", emoji: "🚗" },
      { fr: "Taxi", latin: "Taxi", arabic: "طاكسي", emoji: "🚕" },
      { fr: "Train", latin: "Tran", arabic: "طران", emoji: "🚆" },
      { fr: "Avion", latin: "Tiyara", arabic: "طيارة", emoji: "✈️" },
      { fr: "Bus", latin: "Kar", arabic: "كار", emoji: "🚌" },
      { fr: "Aéroport", latin: "Matar", arabic: "مطار", emoji: "🛫" },
      { fr: "Tout droit", latin: "Nichan", arabic: "نيشان", emoji: "⬆️" },
      { fr: "À droite", latin: "L-limen", arabic: "الليمن", emoji: "➡️" },
      { fr: "À gauche", latin: "L-lisr", arabic: "الليسر", emoji: "⬅️" },
    ],
  },
  {
    id: "meteo",
    label: "Météo & Saisons",
    emoji: "🌦️",
    kidFriendly: false,
    items: [
      { fr: "Il fait chaud", latin: "Skhoun l-jou", arabic: "سخون الجو", emoji: "🥵" },
      { fr: "Il fait froid", latin: "Bared l-jou", arabic: "بارد الجو", emoji: "🥶" },
      { fr: "Il pleut", latin: "Katchti", arabic: "كتشتي", emoji: "🌧️" },
      { fr: "Soleil", latin: "Chms", arabic: "شمس", emoji: "☀️" },
      { fr: "Pluie", latin: "Chta", arabic: "شتا", emoji: "🌧️" },
      { fr: "Nuage", latin: "S7ab", arabic: "سحاب", emoji: "☁️" },
      { fr: "Été", latin: "Sif", arabic: "صيف", emoji: "🏖️" },
      { fr: "Hiver", latin: "Chtwa", arabic: "شتوة", emoji: "❄️" },
      { fr: "Printemps", latin: "Rbi3", arabic: "ربيع", emoji: "🌸" },
      { fr: "Automne", latin: "Kharif", arabic: "خريف", emoji: "🍂" },
    ],
  },
  {
    id: "vetements",
    label: "Vêtements",
    emoji: "👕",
    kidFriendly: false,
    items: [
      { fr: "Vêtements", latin: "Hwayj", arabic: "حوايج", emoji: "👕" },
      { fr: "Chaussures", latin: "Sebbat", arabic: "سبّاط", emoji: "👟" },
      { fr: "T-shirt / Chemise", latin: "Qamija", arabic: "قميجة", emoji: "👕" },
      { fr: "Pantalon", latin: "Serwal", arabic: "سروال", emoji: "👖" },
      { fr: "Djellaba", latin: "Jellaba", arabic: "جلابة", emoji: "🧥" },
      { fr: "Manteau", latin: "Kabbot", arabic: "كابوط", emoji: "🧥" },
    ],
  },
  {
    id: "emotions",
    label: "Émotions",
    emoji: "😊",
    kidFriendly: true,
    items: [
      { fr: "Triste", latin: "Hzin", arabic: "حزين", emoji: "😢" },
      { fr: "En colère", latin: "Ghadban", arabic: "غضبان", emoji: "😠" },
      { fr: "Peur", latin: "Khayef", arabic: "خايف", emoji: "😨" },
      { fr: "Surpris", latin: "Mdhuh", arabic: "مدهوش", emoji: "😲" },
      { fr: "Amoureux", latin: "3achiq", arabic: "عاشق", emoji: "😍" },
      { fr: "Fier", latin: "Fakhur", arabic: "فخور", emoji: "😌" },
    ],
  },
  {
    id: "sante",
    label: "Santé & Urgences",
    emoji: "🚑",
    kidFriendly: false,
    items: [
      { fr: "Docteur", latin: "Tbib", arabic: "طبيب", emoji: "👨‍⚕️" },
      { fr: "Hôpital", latin: "Sbitar", arabic: "سبيطار", emoji: "🏥" },
      { fr: "Pharmacie", latin: "Farmasyan", arabic: "فارماسيان", emoji: "💊" },
      { fr: "Au secours !", latin: "3awnuni!", arabic: "عاونوني!", emoji: "🆘" },
      { fr: "J'ai mal ici", latin: "Kaydarni hna", arabic: "كيضرني هنا", emoji: "🤕" },
      { fr: "Fièvre", latin: "Skhana", arabic: "سخانة", emoji: "🌡️" },
      { fr: "Ça ne va pas", latin: "Machi mzyan", arabic: "ماشي مزيان", emoji: "😷" },
      { fr: "Ambulance", latin: "Ambulans", arabic: "امبولانس", emoji: "🚑" },
    ],
  },
  {
    id: "restaurant",
    label: "Au restaurant",
    emoji: "🍽️",
    kidFriendly: false,
    items: [
      { fr: "L'addition", latin: "L-hsab", arabic: "الحساب", emoji: "🧾" },
      { fr: "Un verre", latin: "Kas", arabic: "كاس", emoji: "🥛" },
      { fr: "Une assiette", latin: "Tbsi", arabic: "طبسي", emoji: "🍽️" },
      { fr: "Cuillère", latin: "M3elqa", arabic: "معلقة", emoji: "🥄" },
      { fr: "Fourchette", latin: "Ferchita", arabic: "فرشيطة", emoji: "🍴" },
      { fr: "Couteau", latin: "Mus", arabic: "موس", emoji: "🔪" },
      { fr: "Sans sucre", latin: "Bla sokkar", arabic: "بلا سكر", emoji: "🚫🍬" },
      { fr: "Avec du lait", latin: "B lhlib", arabic: "بالحليب", emoji: "🥛" },
    ],
  },
  {
    id: "voyage",
    label: "Voyage & Logement",
    emoji: "🧳",
    kidFriendly: false,
    items: [
      { fr: "Hôtel", latin: "Otel", arabic: "أوتيل", emoji: "🏨" },
      { fr: "Valise", latin: "Balisa", arabic: "باليزة", emoji: "🧳" },
      { fr: "Passeport", latin: "Jawaz safar", arabic: "جواز سفر", emoji: "📔" },
      { fr: "Clé", latin: "Saroute", arabic: "سروت", emoji: "🔑" },
      { fr: "J'ai réservé", latin: "7jezt", arabic: "حجزت", emoji: "📅" },
      { fr: "Combien de nuits ?", latin: "Chhal men lila?", arabic: "شحال من ليلة؟", emoji: "🌙" },
    ],
  },
  {
    id: "lieux",
    label: "Lieux en ville",
    emoji: "🏙️",
    kidFriendly: false,
    items: [
      { fr: "Banque", latin: "Banka", arabic: "بنكة", emoji: "🏦" },
      { fr: "Poste", latin: "Bosta", arabic: "بوسطة", emoji: "📮" },
      { fr: "École", latin: "Madrasa", arabic: "مدرسة", emoji: "🏫" },
      { fr: "Mosquée", latin: "Jam3", arabic: "جامع", emoji: "🕌" },
      { fr: "Plage / Mer", latin: "Bhar", arabic: "بحر", emoji: "🏖️" },
      { fr: "Montagne", latin: "Jbel", arabic: "جبل", emoji: "⛰️" },
      { fr: "Ville", latin: "Mdina", arabic: "مدينة", emoji: "🏙️" },
      { fr: "Rue", latin: "Zanka", arabic: "زنقة", emoji: "🛣️" },
    ],
  },
  {
    id: "professions",
    label: "Professions",
    emoji: "💼",
    kidFriendly: false,
    items: [
      { fr: "Travail", latin: "Khedma", arabic: "خدمة", emoji: "💼" },
      { fr: "Professeur", latin: "Ustad", arabic: "أستاذ", emoji: "🧑‍🏫" },
      { fr: "Étudiant", latin: "Talib", arabic: "طالب", emoji: "🧑‍🎓" },
      { fr: "Ingénieur", latin: "Mohandiss", arabic: "مهندس", emoji: "🧑‍💻" },
      { fr: "Cuisinier", latin: "Tabbakh", arabic: "طباخ", emoji: "🧑‍🍳" },
      { fr: "Chauffeur", latin: "Sayeq", arabic: "سايق", emoji: "🚖" },
    ],
  },
];

// Générateur de phrases simples : Sujet (Je) + Verbe + Complément
// Les compléments possibles sont piochés parmi les noms tagués ci-dessus
// (famille, animaux, nourriture) selon ce que le verbe permet ("tags").
const SENTENCE_BUILDER = {
  subject: { fr: "Je", latin: "Ana", arabic: "أنا" },
  verbs: [
    { id: "vouloir", fr: "veux", latin: "bghit", arabic: "بغيت", emoji: "🙏", tag: "any" },
    { id: "aimer", fr: "aime", latin: "kanbghi", arabic: "كنبغي", emoji: "❤️", tag: "any" },
    { id: "voir", fr: "vois", latin: "kanchouf", arabic: "كنشوف", emoji: "👀", tag: "seeable" },
    { id: "manger", fr: "mange", latin: "kanakol", arabic: "كناكل", emoji: "🍽️", tag: "food" },
    { id: "boire", fr: "bois", latin: "kanchrb", arabic: "كنشرب", emoji: "🥤", tag: "drink" },
  ],
};

function getSentenceObjects(tag) {
  return CATEGORIES.flatMap((c) => c.items).filter(
    (item) => item.tags && item.tags.includes(tag)
  );
}
